//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rimss.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConvertedImage
    {
        public ConvertedImage()
        {
            this.FileConversionLogs = new HashSet<FileConversionLog>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid SourceImageId { get; set; }
        public byte[] Data { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public string MetaData { get; set; }
        public string Tag { get; set; }
        public int FormatId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedById { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedById { get; set; }
    
        public virtual SourceImage SourceImage { get; set; }
        public virtual IdentityCache CreatedBy { get; set; }
        public virtual IdentityCache ModifiedBy { get; set; }
        public virtual ICollection<FileConversionLog> FileConversionLogs { get; set; }
        public virtual ImageFormatCode ImageFormatCode { get; set; }
    }
}
