//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rimss.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversionJobLog
    {
        public ConversionJobLog()
        {
            this.FileConversionLogs = new HashSet<FileConversionLog>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ApplicationId { get; set; }
        public int ReasonId { get; private set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedById { get; set; }
        public Nullable<System.DateTime> StartedOn { get; set; }
        public Nullable<System.Guid> StartedById { get; set; }
        public Nullable<System.DateTime> TerminatedOn { get; set; }
        public Nullable<System.Guid> TerminatedById { get; set; }
        public int StatusId { get; set; }
        public string StatusMessage { get; set; }
        public string DetailMessage { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual IdentityCache CreatedBy { get; set; }
        public virtual JobReasonCode JobReasonCode { get; private set; }
        public virtual JobStatusCode JobStatusCode { get; set; }
        public virtual IdentityCache StartedBy { get; set; }
        public virtual IdentityCache TerminatedBy { get; set; }
        public virtual ICollection<FileConversionLog> FileConversionLogs { get; set; }
    }
}
