//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rimss.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobStatusCode
    {
        public JobStatusCode()
        {
            this.ConversionJobLogs = new HashSet<ConversionJobLog>();
            this.FileConversionLogs = new HashSet<FileConversionLog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<ConversionJobLog> ConversionJobLogs { get; set; }
        public virtual ICollection<FileConversionLog> FileConversionLogs { get; set; }
    }
}
