//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rimss.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_JobFileConversionLogListing
    {
        public System.Guid Id { get; set; }
        public System.Guid JobId { get; set; }
        public Nullable<System.DateTime> StartedOn { get; set; }
        public Nullable<System.DateTime> TerminatedOn { get; set; }
        public System.Guid SourceImageId { get; set; }
        public string Tag { get; set; }
        public int FileConversionWidth { get; set; }
        public int FileConversionHeight { get; set; }
        public int FileConversionFormatId { get; set; }
        public string FileConversionFormatName { get; set; }
        public string FileConversionFormatTitle { get; set; }
        public Nullable<System.Guid> ConvertedImageId { get; set; }
        public int ConversionStatusId { get; set; }
        public string ConversionStatusName { get; set; }
        public string ConversionStatusTitle { get; set; }
        public string FileConversionStatusMessage { get; set; }
        public string SourceImageDisplayText { get; set; }
        public string SourceImageName { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public Nullable<int> SourceLength { get; set; }
        public Nullable<int> SourceImageWidth { get; set; }
        public Nullable<int> SourceImageHeight { get; set; }
        public Nullable<int> SourceImageFormatId { get; set; }
        public string SourceImageFormatName { get; set; }
        public string SourceImageFormatTitle { get; set; }
        public Nullable<System.DateTime> SourceImageCreatedOn { get; set; }
        public Nullable<System.Guid> SourceImageCreatedById { get; set; }
        public string SourceImageCreatedByLoginName { get; set; }
        public string SourceImageCreatedByDisplayName { get; set; }
        public Nullable<System.DateTime> SourceImageModifiedOn { get; set; }
        public Nullable<System.Guid> SourceImageModifiedById { get; set; }
        public string SourceImageModifiedByLoginName { get; set; }
        public string SourceImageModifiedByDisplayName { get; set; }
    }
}
