//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rimss.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_FolderListing
    {
        public System.Guid Id { get; set; }
        public string DisplayText { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public System.Guid ApplicationId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedById { get; set; }
        public string CreatedByLoginName { get; set; }
        public string CreatedByDisplayName { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedById { get; set; }
        public string ModifiedByLoginName { get; set; }
        public string ModifiedByDisplayName { get; set; }
        public Nullable<int> ChildFolderCount { get; set; }
        public Nullable<int> SourceImageCount { get; set; }
    }
}
