//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rimss.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SourceFileConversionLogListing
    {
        public System.Guid Id { get; set; }
        public System.Guid JobId { get; set; }
        public Nullable<int> ReasonId { get; set; }
        public string ReasonName { get; set; }
        public string ReasonTitle { get; set; }
        public Nullable<System.DateTime> StartedOn { get; set; }
        public Nullable<System.Guid> StartedById { get; set; }
        public string StartedByLoginName { get; set; }
        public string StartedByDisplayName { get; set; }
        public Nullable<System.DateTime> TerminatedOn { get; set; }
        public System.Guid SourceImageId { get; set; }
        public string Tag { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int FormatId { get; set; }
        public string ImageFormatName { get; set; }
        public string ImageFormatTitle { get; set; }
        public Nullable<System.Guid> ConvertedImageId { get; set; }
        public int ConversionStatusId { get; set; }
        public string ConversionStatusName { get; set; }
        public string ConversionStatusTitle { get; set; }
        public string FileConversionStatusMessage { get; set; }
        public Nullable<int> JobStatusId { get; set; }
        public string JobStatusName { get; set; }
        public string JobStatusTitle { get; set; }
        public string JobStatusMessage { get; set; }
    }
}
