//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rimss.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SystemConvertedImageListing
    {
        public System.Guid Id { get; set; }
        public System.Guid SourceImageId { get; set; }
        public string SourceImageDisplayText { get; set; }
        public string SourceImageName { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public string ApplicationTitle { get; set; }
        public string Tag { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int FormatId { get; set; }
        public string ImageFormatName { get; set; }
        public string ImageFormatTitle { get; set; }
        public Nullable<int> Length { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedById { get; set; }
        public string CreatedByLoginName { get; set; }
        public string CreatedByDisplayName { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedById { get; set; }
        public string ModifiedByLoginName { get; set; }
        public string ModifiedByDisplayName { get; set; }
    }
}
