//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rimss.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.Folders = new HashSet<Folder>();
            this.SourceImages = new HashSet<SourceImage>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedById { get; set; }
        public System.DateTime ModfiedOn { get; set; }
        public System.Guid ModifiedById { get; set; }
    
        public virtual IdentityCache CreatedBy { get; set; }
        public virtual IdentityCache ModifiedBy { get; set; }
        public virtual ICollection<Folder> Folders { get; set; }
        public virtual ICollection<SourceImage> SourceImages { get; set; }
    }
}
