//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rimss.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConvertedImage
    {
        public ConvertedImage()
        {
            this.ConversionLogs = new HashSet<ConversionLog>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid SourceImageId { get; set; }
        public byte[] Data { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int Format { get; set; }
        public string MetaData { get; set; }
        public System.DateTime ConvertedOn { get; set; }
        public System.Guid ConvertedById { get; set; }
        public Nullable<System.DateTime> ExpiresOn { get; set; }
    
        public virtual ICollection<ConversionLog> ConversionLogs { get; set; }
        public virtual IdentityCache ConvertedBy { get; set; }
        public virtual SourceImage SourceImage { get; set; }
    }
}
