//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rimss.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversionJob
    {
        public System.Guid Id { get; set; }
        public System.Guid SourceImageId { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int Format { get; set; }
        public System.DateTime StartedOn { get; set; }
        public System.Guid StartedById { get; set; }
        public int StatusId { get; set; }
        public string StatusMessage { get; set; }
    
        public virtual SourceImage SourceImage { get; set; }
        public virtual IdentityCache StartedBy { get; set; }
    }
}
