//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rimss.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityCache
    {
        public IdentityCache()
        {
            this.CreatedApplications = new HashSet<Application>();
            this.ModifiedApplications = new HashSet<Application>();
            this.ConversionJobs = new HashSet<ConversionJob>();
            this.ConversionLogs = new HashSet<ConversionLog>();
            this.ConvertedImages = new HashSet<ConvertedImage>();
            this.CreatedFolders = new HashSet<Folder>();
            this.ModifiedFolders = new HashSet<Folder>();
            this.CreatedSourceImages = new HashSet<SourceImage>();
            this.ModifiedSourceImages = new HashSet<SourceImage>();
        }
    
        public System.Guid Id { get; set; }
        public byte[] SID { get; set; }
        public string LoginName { get; set; }
        public string DisplayName { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedByLoginName { get; set; }
        public byte[] CreatedBySID { get; set; }
        public System.DateTime VerifiedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedByLoginName { get; set; }
        public byte[] ModifiedBySID { get; set; }
    
        public virtual ICollection<Application> CreatedApplications { get; set; }
        public virtual ICollection<Application> ModifiedApplications { get; set; }
        public virtual ICollection<ConversionJob> ConversionJobs { get; set; }
        public virtual ICollection<ConversionLog> ConversionLogs { get; set; }
        public virtual ICollection<ConvertedImage> ConvertedImages { get; set; }
        public virtual ICollection<Folder> CreatedFolders { get; set; }
        public virtual ICollection<Folder> ModifiedFolders { get; set; }
        public virtual ICollection<SourceImage> CreatedSourceImages { get; set; }
        public virtual ICollection<SourceImage> ModifiedSourceImages { get; set; }
    }
}
