//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rimss.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceImage
    {
        public SourceImage()
        {
            this.ConversionJobs = new HashSet<ConversionJob>();
            this.ConversionLogs = new HashSet<ConversionLog>();
            this.ConvertedImages = new HashSet<ConvertedImage>();
        }
    
        public System.Guid Id { get; set; }
        public string DisplayText { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public System.Guid ApplicationId { get; set; }
        public bool IsPublic { get; set; }
        public byte[] Data { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int Format { get; set; }
        public string MetaData { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedById { get; set; }
        public System.DateTime ModfiedOn { get; set; }
        public System.Guid ModifiedById { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<ConversionJob> ConversionJobs { get; set; }
        public virtual ICollection<ConversionLog> ConversionLogs { get; set; }
        public virtual ICollection<ConvertedImage> ConvertedImages { get; set; }
        public virtual Folder Folder { get; set; }
        public virtual IdentityCache CreatedBy { get; set; }
        public virtual IdentityCache ModifiedBy { get; set; }
    }
}
